services:
  web:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www"
    ports:
      - "80:80"
      - "433:443"
    environment:
      - NGINX_HOST=site.lh
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
  php:
    build: ./etc/php
    working_dir: "/var/www"
    restart: always
    environment:
      - TIMEZONE=UTC
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - oil_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_oil
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app_oil
      - MYSQL_PASSWORD=app1234_oil
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  oil_mysql_data:
  jenkins_home:
