controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_register:
    path: /api/register
    controller: App\Controller\Api\RegistrationController::register
